---
driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: true
  ansible_verbose: false
  ansible_inventory: ./test/integration/inventory
  ansible_vault_password_file: ./test/integration/vault

platforms:
  - name: debian-9
    driver_config:
      image: "nishiki/debian9:ansible-<%= ENV['ANSIBLE_VERSION'] ? ENV['ANSIBLE_VERSION'] : '2.6' %>"
      command: /bin/systemd
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      security_opt: seccomp=unconfined

suites:
  - name: bind
  - name: bind-zones-subset
    provisioner:
      extra_vars:
        bind_zones_subset:
          - test.local
