---
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

env:
  - ANSIBLE_VERSION=2.7.16
  - ANSIBLE_VERSION=2.8.8
  - ANSIBLE_VERSION=2.9.4

services:
  - docker

before_install:
  - sudo pip3 install ansible==${ANSIBLE_VERSION}
  - sudo pip3 install molecule 'molecule[docker]' docker testinfra ansible-lint yamllint
  - git clone https://github.com/ansible/galaxy-lint-rules.git

script:
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
